# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["bhanutejags@gmail.com"]
description = "An API to get the public IP and Geographic information of the user at the edge."
language = "rust"
manifest_version = 2
name = "ifconfig-fastly"
service_id = ""

[setup.log_endpoints."AWS S3 Logging Endpoint"]