name: Deploy Compute@Edge Application
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.59
          target: wasm32-wasi

      - name: Deploy to Compute@Edge
        uses: fastly/compute-actions@main
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
          FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}